version: '3'

services:
  flask:
    container_name: flask-app
    restart: always
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    environment:
      - TZ=Africa/Johannesburg
    ports: -8000:8000
