version: '3'

services:
  flasks:
    container_name: flask-app
    restart: always
    build:
      context: ./flask
      dockerfile: Dockerfile
    environment:
      - TZ=Africa/Johannesburg
    ports:
      - 8000:8000
